#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-json4s_2.11
Version  : 3.5.3
Release  : 2
URL      : https://github.com/json4s/json4s/archive/v3.5.3.tar.gz
Source0  : https://github.com/json4s/json4s/archive/v3.5.3.tar.gz
Source1  : https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.11/3.5.3/json4s-ast_2.11-3.5.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-json4s_2.11-data = %{version}-%{release}

%description
# JSON4S [![Build Status](https://travis-ci.org/json4s/json4s.svg?branch=3.5)](https://travis-ci.org/json4s/json4s)

%package data
Summary: data components for the mvn-json4s_2.11 package.
Group: Data

%description data
data components for the mvn-json4s_2.11 package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-ast_2.11/3.5.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/json4s/json4s-ast_2.11/3.5.3


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/json4s/json4s-ast_2.11/3.5.3/json4s-ast_2.11-3.5.3.pom
